# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('num_bedrooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('posted', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
