# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoods', '0002_auto_20160731_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='border',
            new_name='boundary',
        ),
    ]
